site_name: NFC2BID
site_dir: "\\\\raspidbsrv\\web\\html\\doku\\nfc2bid"
nav:
  - Home: index.md
  - Hardware: hardware.md
  - Firmware:
    - Allgemein: firmware.md
    - BID Speicherstruktur: BID-Speicherstruktur.md
  - About: about.md
  - Hilfe: help.md
theme: 
    name: material
    language: de
    font: false
markdown_extensions:
  - pymdownx.extra
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.codehilite:
      guess_lang: false
      linenums: true

extra_javascript:
    - js/extra.js
    # - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
    - js/MathJax.min.js
